import {AttributeDefinitionDraft} from "@commercetools/platform-sdk";
import {AttributeType} from "@commercetools/platform-sdk/dist/declarations/src/generated/models/product-type";

export const MATERIAL : AttributeType = {
    name: "lenum",
    values: [
        // Filling materials
        {key: "DAUNEN", label: {de: "Daunen", en: "Down"}},
        {key: "FEDERN", label: {de: "Federn", en: "Feathers"}},
        {key: "KUNSTFASER", label: {de: "Kunstfaser", en: "Synthetic fiber"}},
        {key: "KUNSTOFF-WATTIERUNG", label: {de: "Kunstoff-Wattierung", en: "Synthetic padding"}},
        {key: "NATURFASER-WATTIERUNG", label: {de: "Naturfaser-Wattierung", en: "Natural fiber padding"}},
        {key: "OHNE-FUELLUNG", label: {de: "Ohne Füllung", en: "Without filling"}},
        {key: "UNGEFUETTERT", label: {de: "Ungefüttert", en: "Unlined"}},

        // Natural fiber materials
        {key: "ACETAT", label: {de: "Acetat", en: "Acetate"}},
        {key: "ALFA", label: {de: "Alfa", en: "Alfa"}},
        {key: "ALGINAT", label: {de: "Alginat", en: "Alginate"}},
        {key: "ALPAKA", label: {de: "Alpaka", en: "Alpaca"}},
        {key: "LAMA", label: {de: "Lama", en: "Llama"}},
        {key: "KAMEL", label: {de: "Kamel", en: "Camel"}},
        {key: "MOHAIR", label: {de: "Mohair", en: "Mohair"}},
        {key: "ANGORA", label: {de: "Angora", en: "Angora"}},
        {key: "VIKUNJA", label: {de: "Vikunja", en: "Vicuña"}},
        {key: "YAK", label: {de: "Yak", en: "Yak"}},
        {key: "GUANAKO", label: {de: "Guanako", en: "Guanaco"}},
        {key: "KASCHGORA", label: {de: "Kaschgora", en: "Kashgora"}},
        {key: "BIBER", label: {de: "Biber", en: "Beaver"}},
        {key: "FISCHOTTER", label: {de: "Fischotter", en: "Otter"}},
        {key: "ANDERE-FASERN", label: {de: "Andere Fasern", en: "Other fibers"}},

        // Synthetic materials
        {key: "ARAMID", label: {de: "Aramid", en: "Aramid"}},
        {key: "BAUMWOLLE", label: {de: "Baumwolle", en: "Cotton"}},
        {key: "BAUMWOLLE-BIO", label: {de: "Baumwolle (Bio)", en: "Organic cotton"}},
        {key: "BAUMWOLLE-RECYCELT", label: {de: "Baumwolle (Recycelt)", en: "Recycled cotton"}},
        {key: "BAUMWOLLE-PIMABAUMWOLLE", label: {de: "Baumwolle (Pima)", en: "Pima cotton"}},
        {key: "CUPRO", label: {de: "Cupro", en: "Cupro"}},
        {key: "ELASTHAN", label: {de: "Elasthan", en: "Elastane"}},
        {key: "ELASTHAN-RECYCELT", label: {de: "Elasthan (recycelt)", en: "Recycled elastane"}},
        {key: "ELASTODIEN", label: {de: "Elastodien", en: "Elastodiene"}},
        {key: "ELASTOLEFIN", label: {de: "Elastolefin", en: "Elastolefin"}},
        {key: "ELASTOMULTIESTER", label: {de: "Elastomultiester", en: "Elastomultiester"}},
        {key: "FLACHS", label: {de: "Flachs", en: "Flax"}},
        {key: "FLUORFASER", label: {de: "Fluorfaser", en: "Fluorofiber"}},
        {key: "GINSTER", label: {de: "Ginster", en: "Broom"}},
        {key: "GLASFASER", label: {de: "Glasfaser", en: "Glass fiber"}},
        {key: "HANF", label: {de: "Hanf", en: "Hemp"}},
        {key: "HENEQUEN", label: {de: "Henequen", en: "Henequen"}},
        {key: "JUTE", label: {de: "Jute", en: "Jute"}},
        {key: "KAPOK", label: {de: "Kapok", en: "Kapok"}},
        {key: "KASCHMIR", label: {de: "Kaschmir", en: "Cashmere"}},
        {key: "KASCHMIR-RECYCELT", label: {de: "Kaschmir (recycelt)", en: "Recycled cashmere"}},
        {key: "KOKOS", label: {de: "Kokos", en: "Coconut"}},
        {key: "LAMMFELL", label: {de: "Lammfell", en: "Lambskin"}},
        {key: "LYOCELL", label: {de: "Lyocell", en: "Lyocell"}},
        {key: "MAGUEY", label: {de: "Maguey", en: "Maguey"}},
        {key: "MANILA", label: {de: "Manila", en: "Manila"}},
        {key: "MELAMIN", label: {de: "Melamin", en: "Melamine"}},
        {key: "METALLFASER", label: {de: "Metallfaser", en: "Metal fiber"}},
        {key: "MODACRYL", label: {de: "Modacryl", en: "Modacrylic"}},
        {key: "MODAL", label: {de: "Modal", en: "Modal"}},
        {key: "NYLON", label: {de: "Nylon", en: "Nylon"}},
        {key: "NYLON-RECYCELT", label: {de: "Nylon (Recycelt)", en: "Recycled nylon"}},
        {key: "POLYACRYL", label: {de: "Polyacryl", en: "Polyacrylic"}},
        {key: "POLYCHLORID", label: {de: "Polychlorid", en: "Polychloride"}},
        {key: "POLYCHLOROPREN", label: {de: "POLYCHLOROPREN", en: "Polychloroprene"}},
        {key: "POLYESTER", label: {de: "Polyester", en: "Polyester"}},
        {key: "POLYESTER-RECYCELT", label: {de: "Polyester (Recycelt)", en: "Recycled polyester"}},
        {key: "POLYETHYLEN", label: {de: "Polyethylen", en: "Polyethylene"}},
        {key: "POLYHARNSTOFF", label: {de: "Polyharnstoff", en: "Polyurea"}},
        {key: "POLYIMID", label: {de: "Polyimid", en: "Polyimide"}},
        {key: "POLYLACTID", label: {de: "Polylactid", en: "Polylactide"}},
        {key: "POLYPROPYLEN", label: {de: "Polypropylen", en: "Polypropylene"}},
        {key: "POLYTETRAFLUORETHYLEN", label: {de: "Polytetrafluorethylen", en: "Polytetrafluoroethylene"}},
        {key: "POLYVINYLCHLORID", label: {de: "Polyvinylchlorid", en: "Polyvinyl chloride"}},
        {key: "RAMIE", label: {de: "Ramie", en: "Ramie"}},
        {key: "REGENERIERTE-PROTEINFASER", label: {de: "Regenerierte Proteinfaser", en: "Regenerated protein fiber"}},
        {key: "SISAL", label: {de: "Sisal", en: "Sisal"}},
        {key: "TRIACETAT", label: {de: "Triacetat", en: "Triacetate"}},
        {key: "TRIVINYL", label: {de: "Trivinyl", en: "Trivinyl"}},
        {key: "VINYLAL", label: {de: "Vinylal", en: "Vinylal"}},
        {key: "VISKOSE", label: {de: "Viskose", en: "Viscose"}},
        {key: "VISKOSE-RECYCELT", label: {de: "Viskose (Recycelt)", en: "Recycled viscose"}},
        {key: "WOLLE", label: {de: "Wolle", en: "Wool"}},
        {key: "WOLLE-BIO", label: {de: "Wolle (Bio)", en: "Organic wool"}},
        {key: "WOLLE-RECYCELT", label: {de: "Wolle (Recycelt)", en: "Recycled wool"}},
        {key: "WOLLE-MERINO", label: {de: "Wolle (Merino)", en: "Merino wool"}},
        {key: "SCHURWOLLE", label: {de: "Schurwolle", en: "Virgin wool"}},
        {key: "SCHURWOLLE-RECYCELT", label: {de: "Schurwolle (Recycelt)", en: "Recycled virgin wool"}},

        // Fur and leather materials
        {key: "ECHTPELZ", label: {de: "Echtpelz", en: "Real fur"}},
        {key: "PELZ-HASE", label: {de: "Pelz (Hase)", en: "Rabbit fur"}},
        {key: "PELZ-FUCHS", label: {de: "Pelz (Fuchs)", en: "Fox fur"}},
        {key: "PELZ-WASCHBAER", label: {de: "Pelz (Waschbär)", en: "Raccoon fur"}},
        {key: "PELZ-BIBER", label: {de: "Pelz (Biber)", en: "Beaver fur"}},
        {key: "PELZ-NERZ", label: {de: "Pelz (Nerz)", en: "Mink fur"}},
        {key: "PELZ-MARDER", label: {de: "Pelz (Marder)", en: "Marten fur"}},
        {key: "PELZ-DACHS", label: {de: "Pelz (Dachs)", en: "Badger fur"}},
        {key: "PELZ-WIESEL", label: {de: "Pelz (Wiesel)", en: "Weasel fur"}},
        {key: "PELZ-ILTIS", label: {de: "Pelz (Iltis)", en: "Polecat fur"}},
        {key: "LEDER", label: {de: "Leder", en: "Leather"}},
        {key: "GLATTLEDER", label: {de: "Leder (glatt)", en: "Smooth leather"}},
        {key: "RAULEDER", label: {de: "Leder (rau)", en: "Rough leather"}},
        {key: "LEDERIMITAT", label: {de: "Lederimitat", en: "Leather imitation"}},
        {key: "LEDER-RECYCELT", label: {de: "Leder (recycelt)", en: "Recycled leather"}},
        {key: "LEDER-ZERTIFIZIERT", label: {de: "Leder (zertifiziert)", en: "Certified leather"}},

        // Other materials
        {key: "PVC", label: {de: "PVC", en: "PVC"}},
        {key: "KORK", label: {de: "Kork", en: "Cork"}},
        {key: "BAST", label: {de: "Bast", en: "Bast"}},
        {key: "CANVAS", label: {de: "Canvas", en: "Canvas"}},
        {key: "CORD", label: {de: "Cord", en: "Corduroy"}},
        {key: "JEANS", label: {de: "Denim", en: "Denim"}},
        {key: "GUMMI", label: {de: "Gummi", en: "Rubber"}},
        {key: "HOLZ", label: {de: "Holz", en: "Wood"}},
        {key: "KERAMIK", label: {de: "Keramik", en: "Ceramic"}},
        {key: "KUNSTSTOFF", label: {de: "Kunststoff", en: "Plastic"}},
        {key: "LACK", label: {de: "Lack", en: "Lacquer"}},
        {key: "LEINEN", label: {de: "Leinen", en: "Linen"}},
        {key: "METALL", label: {de: "Metall", en: "Metal"}},
        {key: "POLYAMID", label: {de: "Polyamid", en: "Polyamide"}},
        {key: "POLYAMID-RECYCELT", label: {de: "Polyamid (Recycelt)", en: "Recycled polyamide"}},
        {key: "POLYURETHAN", label: {de: "Polyurethan", en: "Polyurethane"}},
        {key: "SAMT", label: {de: "Samt", en: "Velvet"}},
        {key: "SATIN", label: {de: "Satin", en: "Satin"}},
        {key: "SEIDE", label: {de: "Seide", en: "Silk"}},
        {key: "SPITZE", label: {de: "Spitze", en: "Lace"}},
        {key: "TEXTIL", label: {de: "Textil", en: "Textile"}},
        {key: "SILIKON", label: {de: "Silikon", en: "Silicone"}},
        {key: "ALUMINIUM", label: {de: "Aluminium", en: "Aluminum"}},
        {key: "EDELSTAHL", label: {de: "Edelstahl", en: "Stainless steel"}},

        // Metals and precious materials
        {key: "GOLD", label: {de: "Gold", en: "Gold"}},
        {key: "GELBGOLD-333", label: {de: "Gelbgold 333", en: "Yellow gold 333"}},
        {key: "GELBGOLD-375", label: {de: "Gelbgold 375", en: "Yellow gold 375"}},
        {key: "GELBGOLD-585", label: {de: "Gelbgold 585", en: "Yellow gold 585"}},
        {key: "GELBGOLD-750", label: {de: "Gelbgold 750", en: "Yellow gold 750"}},
        {key: "WEISSGOLD-333", label: {de: "Weißgold 333", en: "White gold 333"}},
        {key: "WEISSGOLD-375", label: {de: "Weißgold 375", en: "White gold 375"}},
        {key: "WEISSGOLD-585", label: {de: "Weißgold 585", en: "White gold 585"}},
        {key: "WEISSGOLD-750", label: {de: "Weißgold 750", en: "White gold 750"}},
        {key: "ROSEGOLD", label: {de: "Roségold", en: "Rose gold"}},
        {key: "ROSEGOLD-333", label: {de: "Roségold 333", en: "Rose gold 333"}},
        {key: "ROSEGOLD-375", label: {de: "Roségold 375", en: "Rose gold 375"}},
        {key: "ROSEGOLD-585", label: {de: "Roségold 585", en: "Rose gold 585"}},
        {key: "ROSEGOLD-750", label: {de: "Roségold 750", en: "Rose gold 750"}},
        {key: "ROTGOLD-333", label: {de: "Rotgold 333", en: "Red gold 333"}},
        {key: "ROTGOLD-375", label: {de: "Rotgold 375", en: "Red gold 375"}},
        {key: "ROTGOLD-585", label: {de: "Rotgold 585", en: "Red gold 585"}},
        {key: "ROTGOLD-750", label: {de: "Rotgold 750", en: "Red gold 750"}},
        {key: "SILBER", label: {de: "Silber", en: "Silver"}},
        {key: "SILBER-925", label: {de: "925er Silber", en: "925 Silver"}},
        {key: "MESSING", label: {de: "Messing", en: "Brass"}},
        {key: "NICKEL", label: {de: "Nickel", en: "Nickel"}},
        {key: "TITAN", label: {de: "Titan", en: "Titanium"}},

        // Glass and technical materials
        {key: "MINERALGLAS", label: {de: "Mineralglas", en: "Mineral glass"}},
        {key: "SAPHRIGLAS", label: {de: "Saphriglas", en: "Sapphire glass"}},
        {key: "POLYCARBONAT", label: {de: "Polycarbonat", en: "Polycarbonate"}},
        {key: "CARBON", label: {de: "Carbon", en: "Carbon"}},
        {key: "EVAC", label: {de: "EVAC", en: "EVAC"}},

        // Animal materials
        {key: "ZIEGENFELL", label: {de: "Ziegenfell", en: "Goat skin"}},
        {key: "TIERHAAR", label: {de: "Tierhaar", en: "Animal hair"}},
        {key: "RINDERHAAR", label: {de: "Rinderhaar", en: "Cattle hair"}},
        {key: "ZIEGENHAAR", label: {de: "Ziegenhaar", en: "Goat hair"}},
        {key: "PFERDEHAAR", label: {de: "Pferdehaar", en: "Horse hair"}},
        {key: "ENTENDAUNEN-RECYCELT", label: {de: "Entendaunen (recycelt)", en: "Recycled duck down"}},
        {key: "ENTENDAUNEN-ZERTIFIZIERT", label: {de: "Entendaunen (zertifiziert)", en: "Certified duck down"}},

        // Special materials
        {key: "BAMBUS", label: {de: "Bambus", en: "Bamboo"}},
        {key: "PAPIERFASERN", label: {de: "Papierfasern", en: "Paper fibers"}},
        {key: "POLYACRYLAT", label: {de: "Polyacrylat", en: "Polyacrylate"}},
        {key: "POLYACTID", label: {de: "Polyactid", en: "Polyactide"}},
        {key: "POLYBUTYLENTEREPHTHALAT", label: {de: "Polybutylenterephthalat", en: "Polybutylene terephthalate"}},
        {key: "SEACELL-LYOCELL", label: {de: "Seacell Lyocell", en: "Seacell Lyocell"}},
        {key: "COREVA", label: {de: "Coreva", en: "Coreva"}},
        {key: "WOOLTEN", label: {de: "Woolten", en: "Woolten"}},
        {key: "SORONA", label: {de: "Sorona", en: "Sorona"}},
        {key: "ASBEST", label: {de: "Asbest", en: "Asbestos"}},

        // Instructions
        {key: "MATERIAL_INSTRUCTIONS_FEATURE_YES", label: {de: "Enthält nichttextile Teile tierischen Ursprungs", en: "Contains non-textile parts of animal origin"}},
        {key: "MATERIAL_INSTRUCTIONS_FEATURE_NO", label: {de: "Enthält keine nichttextilen Teile tierischen Ursprungs", en: "Contains no non-textile parts of animal origin"}},

        // Other
        {key: "SONSTIGES", label: {de: "Sonstiges", en: "Other"}}
    ]
}