
import { LocalizedString } from "@commercetools/platform-sdk";

export interface MaterialValue {
    key: string;
    label: LocalizedString;
}

export const MATERIAL_VALUES: Record<string, MaterialValue> = {
    // Filling materials
    DAUNEN: {key: "DAUNEN", label: {de: "Daunen", en: "Down"}},
    FEDERN: {key: "FEDERN", label: {de: "Federn", en: "Feathers"}},
    KUNSTFASER: {key: "KUNSTFASER", label: {de: "Kunstfaser", en: "Synthetic fiber"}},
    "KUNSTOFF-WATTIERUNG": {key: "KUNSTOFF-WATTIERUNG", label: {de: "Kunstoff-Wattierung", en: "Synthetic padding"}},
    "NATURFASER-WATTIERUNG": {key: "NATURFASER-WATTIERUNG", label: {de: "Naturfaser-Wattierung", en: "Natural fiber padding"}},
    "OHNE-FUELLUNG": {key: "OHNE-FUELLUNG", label: {de: "Ohne Füllung", en: "Without filling"}},
    UNGEFUETTERT: {key: "UNGEFUETTERT", label: {de: "Ungefüttert", en: "Unlined"}},

    // Natural fiber materials
    ACETAT: {key: "ACETAT", label: {de: "Acetat", en: "Acetate"}},
    ALFA: {key: "ALFA", label: {de: "Alfa", en: "Alfa"}},
    ALGINAT: {key: "ALGINAT", label: {de: "Alginat", en: "Alginate"}},
    ALPAKA: {key: "ALPAKA", label: {de: "Alpaka", en: "Alpaca"}},
    LAMA: {key: "LAMA", label: {de: "Lama", en: "Llama"}},
    KAMEL: {key: "KAMEL", label: {de: "Kamel", en: "Camel"}},
    MOHAIR: {key: "MOHAIR", label: {de: "Mohair", en: "Mohair"}},
    ANGORA: {key: "ANGORA", label: {de: "Angora", en: "Angora"}},
    VIKUNJA: {key: "VIKUNJA", label: {de: "Vikunja", en: "Vicuña"}},
    YAK: {key: "YAK", label: {de: "Yak", en: "Yak"}},
    GUANAKO: {key: "GUANAKO", label: {de: "Guanako", en: "Guanaco"}},
    KASCHGORA: {key: "KASCHGORA", label: {de: "Kaschgora", en: "Kashgora"}},
    BIBER: {key: "BIBER", label: {de: "Biber", en: "Beaver"}},
    FISCHOTTER: {key: "FISCHOTTER", label: {de: "Fischotter", en: "Otter"}},
    "ANDERE-FASERN": {key: "ANDERE-FASERN", label: {de: "Andere Fasern", en: "Other fibers"}},

    // Synthetic materials
    ARAMID: {key: "ARAMID", label: {de: "Aramid", en: "Aramid"}},
    BAUMWOLLE: {key: "BAUMWOLLE", label: {de: "Baumwolle", en: "Cotton"}},
    "BAUMWOLLE-BIO": {key: "BAUMWOLLE-BIO", label: {de: "Baumwolle (Bio)", en: "Organic cotton"}},
    "BAUMWOLLE-RECYCELT": {key: "BAUMWOLLE-RECYCELT", label: {de: "Baumwolle (Recycelt)", en: "Recycled cotton"}},
    "BAUMWOLLE-PIMABAUMWOLLE": {key: "BAUMWOLLE-PIMABAUMWOLLE", label: {de: "Baumwolle (Pima)", en: "Pima cotton"}},
    CUPRO: {key: "CUPRO", label: {de: "Cupro", en: "Cupro"}},
    ELASTHAN: {key: "ELASTHAN", label: {de: "Elasthan", en: "Elastane"}},
    "ELASTHAN-RECYCELT": {key: "ELASTHAN-RECYCELT", label: {de: "Elasthan (recycelt)", en: "Recycled elastane"}},
    ELASTODIEN: {key: "ELASTODIEN", label: {de: "Elastodien", en: "Elastodiene"}},
    ELASTOLEFIN: {key: "ELASTOLEFIN", label: {de: "Elastolefin", en: "Elastolefin"}},
    ELASTOMULTIESTER: {key: "ELASTOMULTIESTER", label: {de: "Elastomultiester", en: "Elastomultiester"}},
    FLACHS: {key: "FLACHS", label: {de: "Flachs", en: "Flax"}},
    FLUORFASER: {key: "FLUORFASER", label: {de: "Fluorfaser", en: "Fluorofiber"}},
    GINSTER: {key: "GINSTER", label: {de: "Ginster", en: "Broom"}},
    GLASFASER: {key: "GLASFASER", label: {de: "Glasfaser", en: "Glass fiber"}},
    HANF: {key: "HANF", label: {de: "Hanf", en: "Hemp"}},
    HENEQUEN: {key: "HENEQUEN", label: {de: "Henequen", en: "Henequen"}},
    JUTE: {key: "JUTE", label: {de: "Jute", en: "Jute"}},
    KAPOK: {key: "KAPOK", label: {de: "Kapok", en: "Kapok"}},
    KASCHMIR: {key: "KASCHMIR", label: {de: "Kaschmir", en: "Cashmere"}},
    "KASCHMIR-RECYCELT": {key: "KASCHMIR-RECYCELT", label: {de: "Kaschmir (recycelt)", en: "Recycled cashmere"}},
    KOKOS: {key: "KOKOS", label: {de: "Kokos", en: "Coconut"}},
    LAMMFELL: {key: "LAMMFELL", label: {de: "Lammfell", en: "Lambskin"}},
    LYOCELL: {key: "LYOCELL", label: {de: "Lyocell", en: "Lyocell"}},
    MAGUEY: {key: "MAGUEY", label: {de: "Maguey", en: "Maguey"}},
    MANILA: {key: "MANILA", label: {de: "Manila", en: "Manila"}},
    MELAMIN: {key: "MELAMIN", label: {de: "Melamin", en: "Melamine"}},
    METALLFASER: {key: "METALLFASER", label: {de: "Metallfaser", en: "Metal fiber"}},
    MODACRYL: {key: "MODACRYL", label: {de: "Modacryl", en: "Modacrylic"}},
    MODAL: {key: "MODAL", label: {de: "Modal", en: "Modal"}},
    NYLON: {key: "NYLON", label: {de: "Nylon", en: "Nylon"}},
    "NYLON-RECYCELT": {key: "NYLON-RECYCELT", label: {de: "Nylon (Recycelt)", en: "Recycled nylon"}},
    POLYACRYL: {key: "POLYACRYL", label: {de: "Polyacryl", en: "Polyacrylic"}},
    POLYCHLORID: {key: "POLYCHLORID", label: {de: "Polychlorid", en: "Polychloride"}},
    POLYCHLOROPREN: {key: "POLYCHLOROPREN", label: {de: "POLYCHLOROPREN", en: "Polychloroprene"}},
    POLYESTER: {key: "POLYESTER", label: {de: "Polyester", en: "Polyester"}},
    "POLYESTER-RECYCELT": {key: "POLYESTER-RECYCELT", label: {de: "Polyester (Recycelt)", en: "Recycled polyester"}},
    POLYETHYLEN: {key: "POLYETHYLEN", label: {de: "Polyethylen", en: "Polyethylene"}},
    POLYHARNSTOFF: {key: "POLYHARNSTOFF", label: {de: "Polyharnstoff", en: "Polyurea"}},
    POLYIMID: {key: "POLYIMID", label: {de: "Polyimid", en: "Polyimide"}},
    POLYLACTID: {key: "POLYLACTID", label: {de: "Polylactid", en: "Polylactide"}},
    POLYPROPYLEN: {key: "POLYPROPYLEN", label: {de: "Polypropylen", en: "Polypropylene"}},
    POLYTETRAFLUORETHYLEN: {key: "POLYTETRAFLUORETHYLEN", label: {de: "Polytetrafluorethylen", en: "Polytetrafluoroethylene"}},
    POLYVINYLCHLORID: {key: "POLYVINYLCHLORID", label: {de: "Polyvinylchlorid", en: "Polyvinyl chloride"}},
    RAMIE: {key: "RAMIE", label: {de: "Ramie", en: "Ramie"}},
    "REGENERIERTE-PROTEINFASER": {key: "REGENERIERTE-PROTEINFASER", label: {de: "Regenerierte Proteinfaser", en: "Regenerated protein fiber"}},
    SISAL: {key: "SISAL", label: {de: "Sisal", en: "Sisal"}},
    TRIACETAT: {key: "TRIACETAT", label: {de: "Triacetat", en: "Triacetate"}},
    TRIVINYL: {key: "TRIVINYL", label: {de: "Trivinyl", en: "Trivinyl"}},
    VINYLAL: {key: "VINYLAL", label: {de: "Vinylal", en: "Vinylal"}},
    VISKOSE: {key: "VISKOSE", label: {de: "Viskose", en: "Viscose"}},
    "VISKOSE-RECYCELT": {key: "VISKOSE-RECYCELT", label: {de: "Viskose (Recycelt)", en: "Recycled viscose"}},
    WOLLE: {key: "WOLLE", label: {de: "Wolle", en: "Wool"}},
    "WOLLE-BIO": {key: "WOLLE-BIO", label: {de: "Wolle (Bio)", en: "Organic wool"}},
    "WOLLE-RECYCELT": {key: "WOLLE-RECYCELT", label: {de: "Wolle (Recycelt)", en: "Recycled wool"}},
    "WOLLE-MERINO": {key: "WOLLE-MERINO", label: {de: "Wolle (Merino)", en: "Merino wool"}},
    SCHURWOLLE: {key: "SCHURWOLLE", label: {de: "Schurwolle", en: "Virgin wool"}},
    "SCHURWOLLE-RECYCELT": {key: "SCHURWOLLE-RECYCELT", label: {de: "Schurwolle (Recycelt)", en: "Recycled virgin wool"}},

    // Fur and leather materials
    ECHTPELZ: {key: "ECHTPELZ", label: {de: "Echtpelz", en: "Real fur"}},
    "PELZ-HASE": {key: "PELZ-HASE", label: {de: "Pelz (Hase)", en: "Rabbit fur"}},
    "PELZ-FUCHS": {key: "PELZ-FUCHS", label: {de: "Pelz (Fuchs)", en: "Fox fur"}},
    "PELZ-WASCHBAER": {key: "PELZ-WASCHBAER", label: {de: "Pelz (Waschbär)", en: "Raccoon fur"}},
    "PELZ-BIBER": {key: "PELZ-BIBER", label: {de: "Pelz (Biber)", en: "Beaver fur"}},
    "PELZ-NERZ": {key: "PELZ-NERZ", label: {de: "Pelz (Nerz)", en: "Mink fur"}},
    "PELZ-MARDER": {key: "PELZ-MARDER", label: {de: "Pelz (Marder)", en: "Marten fur"}},
    "PELZ-DACHS": {key: "PELZ-DACHS", label: {de: "Pelz (Dachs)", en: "Badger fur"}},
    "PELZ-WIESEL": {key: "PELZ-WIESEL", label: {de: "Pelz (Wiesel)", en: "Weasel fur"}},
    "PELZ-ILTIS": {key: "PELZ-ILTIS", label: {de: "Pelz (Iltis)", en: "Polecat fur"}},
    LEDER: {key: "LEDER", label: {de: "Leder", en: "Leather"}},
    GLATTLEDER: {key: "GLATTLEDER", label: {de: "Leder (glatt)", en: "Smooth leather"}},
    RAULEDER: {key: "RAULEDER", label: {de: "Leder (rau)", en: "Rough leather"}},
    LEDERIMITAT: {key: "LEDERIMITAT", label: {de: "Lederimitat", en: "Leather imitation"}},
    "LEDER-RECYCELT": {key: "LEDER-RECYCELT", label: {de: "Leder (recycelt)", en: "Recycled leather"}},
    "LEDER-ZERTIFIZIERT": {key: "LEDER-ZERTIFIZIERT", label: {de: "Leder (zertifiziert)", en: "Certified leather"}},

    // Other materials
    PVC: {key: "PVC", label: {de: "PVC", en: "PVC"}},
    KORK: {key: "KORK", label: {de: "Kork", en: "Cork"}},
    BAST: {key: "BAST", label: {de: "Bast", en: "Bast"}},
    CANVAS: {key: "CANVAS", label: {de: "Canvas", en: "Canvas"}},
    CORD: {key: "CORD", label: {de: "Cord", en: "Corduroy"}},
    JEANS: {key: "JEANS", label: {de: "Denim", en: "Denim"}},
    GUMMI: {key: "GUMMI", label: {de: "Gummi", en: "Rubber"}},
    HOLZ: {key: "HOLZ", label: {de: "Holz", en: "Wood"}},
    KERAMIK: {key: "KERAMIK", label: {de: "Keramik", en: "Ceramic"}},
    KUNSTSTOFF: {key: "KUNSTSTOFF", label: {de: "Kunststoff", en: "Plastic"}},
    LACK: {key: "LACK", label: {de: "Lack", en: "Lacquer"}},
    LEINEN: {key: "LEINEN", label: {de: "Leinen", en: "Linen"}},
    METALL: {key: "METALL", label: {de: "Metall", en: "Metal"}},
    POLYAMID: {key: "POLYAMID", label: {de: "Polyamid", en: "Polyamide"}},
    "POLYAMID-RECYCELT": {key: "POLYAMID-RECYCELT", label: {de: "Polyamid (Recycelt)", en: "Recycled polyamide"}},
    POLYURETHAN: {key: "POLYURETHAN", label: {de: "Polyurethan", en: "Polyurethane"}},
    SAMT: {key: "SAMT", label: {de: "Samt", en: "Velvet"}},
    SATIN: {key: "SATIN", label: {de: "Satin", en: "Satin"}},
    SEIDE: {key: "SEIDE", label: {de: "Seide", en: "Silk"}},
    SPITZE: {key: "SPITZE", label: {de: "Spitze", en: "Lace"}},
    TEXTIL: {key: "TEXTIL", label: {de: "Textil", en: "Textile"}},
    SILIKON: {key: "SILIKON", label: {de: "Silikon", en: "Silicone"}},
    ALUMINIUM: {key: "ALUMINIUM", label: {de: "Aluminium", en: "Aluminum"}},
    EDELSTAHL: {key: "EDELSTAHL", label: {de: "Edelstahl", en: "Stainless steel"}},

    // Metals and precious materials
    GOLD: {key: "GOLD", label: {de: "Gold", en: "Gold"}},
    "GELBGOLD-333": {key: "GELBGOLD-333", label: {de: "Gelbgold 333", en: "Yellow gold 333"}},
    "GELBGOLD-375": {key: "GELBGOLD-375", label: {de: "Gelbgold 375", en: "Yellow gold 375"}},
    "GELBGOLD-585": {key: "GELBGOLD-585", label: {de: "Gelbgold 585", en: "Yellow gold 585"}},
    "GELBGOLD-750": {key: "GELBGOLD-750", label: {de: "Gelbgold 750", en: "Yellow gold 750"}},
    "WEISSGOLD-333": {key: "WEISSGOLD-333", label: {de: "Weißgold 333", en: "White gold 333"}},
    "WEISSGOLD-375": {key: "WEISSGOLD-375", label: {de: "Weißgold 375", en: "White gold 375"}},
    "WEISSGOLD-585": {key: "WEISSGOLD-585", label: {de: "Weißgold 585", en: "White gold 585"}},
    "WEISSGOLD-750": {key: "WEISSGOLD-750", label: {de: "Weißgold 750", en: "White gold 750"}},
    ROSEGOLD: {key: "ROSEGOLD", label: {de: "Roségold", en: "Rose gold"}},
    "ROSEGOLD-333": {key: "ROSEGOLD-333", label: {de: "Roségold 333", en: "Rose gold 333"}},
    "ROSEGOLD-375": {key: "ROSEGOLD-375", label: {de: "Roségold 375", en: "Rose gold 375"}},
    "ROSEGOLD-585": {key: "ROSEGOLD-585", label: {de: "Roségold 585", en: "Rose gold 585"}},
    "ROSEGOLD-750": {key: "ROSEGOLD-750", label: {de: "Roségold 750", en: "Rose gold 750"}},
    "ROTGOLD-333": {key: "ROTGOLD-333", label: {de: "Rotgold 333", en: "Red gold 333"}},
    "ROTGOLD-375": {key: "ROTGOLD-375", label: {de: "Rotgold 375", en: "Red gold 375"}},
    "ROTGOLD-585": {key: "ROTGOLD-585", label: {de: "Rotgold 585", en: "Red gold 585"}},
    "ROTGOLD-750": {key: "ROTGOLD-750", label: {de: "Rotgold 750", en: "Red gold 750"}},
    SILBER: {key: "SILBER", label: {de: "Silber", en: "Silver"}},
    "SILBER-925": {key: "SILBER-925", label: {de: "925er Silber", en: "925 Silver"}},
    MESSING: {key: "MESSING", label: {de: "Messing", en: "Brass"}},
    NICKEL: {key: "NICKEL", label: {de: "Nickel", en: "Nickel"}},
    TITAN: {key: "TITAN", label: {de: "Titan", en: "Titanium"}},

    // Glass and technical materials
    MINERALGLAS: {key: "MINERALGLAS", label: {de: "Mineralglas", en: "Mineral glass"}},
    SAPHRIGLAS: {key: "SAPHRIGLAS", label: {de: "Saphriglas", en: "Sapphire glass"}},
    POLYCARBONAT: {key: "POLYCARBONAT", label: {de: "Polycarbonat", en: "Polycarbonate"}},
    CARBON: {key: "CARBON", label: {de: "Carbon", en: "Carbon"}},
    EVAC: {key: "EVAC", label: {de: "EVAC", en: "EVAC"}},

    // Animal materials
    ZIEGENFELL: {key: "ZIEGENFELL", label: {de: "Ziegenfell", en: "Goat skin"}},
    TIERHAAR: {key: "TIERHAAR", label: {de: "Tierhaar", en: "Animal hair"}},
    RINDERHAAR: {key: "RINDERHAAR", label: {de: "Rinderhaar", en: "Cattle hair"}},
    ZIEGENHAAR: {key: "ZIEGENHAAR", label: {de: "Ziegenhaar", en: "Goat hair"}},
    PFERDEHAAR: {key: "PFERDEHAAR", label: {de: "Pferdehaar", en: "Horse hair"}},
    "ENTENDAUNEN-RECYCELT": {key: "ENTENDAUNEN-RECYCELT", label: {de: "Entendaunen (recycelt)", en: "Recycled duck down"}},
    "ENTENDAUNEN-ZERTIFIZIERT": {key: "ENTENDAUNEN-ZERTIFIZIERT", label: {de: "Entendaunen (zertifiziert)", en: "Certified duck down"}},

    // Special materials
    BAMBUS: {key: "BAMBUS", label: {de: "Bambus", en: "Bamboo"}},
    PAPIERFASERN: {key: "PAPIERFASERN", label: {de: "Papierfasern", en: "Paper fibers"}},
    POLYACRYLAT: {key: "POLYACRYLAT", label: {de: "Polyacrylat", en: "Polyacrylate"}},
    POLYACTID: {key: "POLYACTID", label: {de: "Polyactid", en: "Polyactide"}},
    POLYBUTYLENTEREPHTHALAT: {key: "POLYBUTYLENTEREPHTHALAT", label: {de: "Polybutylenterephthalat", en: "Polybutylene terephthalate"}},
    "SEACELL-LYOCELL": {key: "SEACELL-LYOCELL", label: {de: "Seacell Lyocell", en: "Seacell Lyocell"}},
    COREVA: {key: "COREVA", label: {de: "Coreva", en: "Coreva"}},
    WOOLTEN: {key: "WOOLTEN", label: {de: "Woolten", en: "Woolten"}},
    SORONA: {key: "SORONA", label: {de: "Sorona", en: "Sorona"}},
    ASBEST: {key: "ASBEST", label: {de: "Asbest", en: "Asbestos"}},

    // Instructions
    MATERIAL_INSTRUCTIONS_FEATURE_YES: {key: "MATERIAL_INSTRUCTIONS_FEATURE_YES", label: {de: "Enthält nichttextile Teile tierischen Ursprungs", en: "Contains non-textile parts of animal origin"}},
    MATERIAL_INSTRUCTIONS_FEATURE_NO: {key: "MATERIAL_INSTRUCTIONS_FEATURE_NO", label: {de: "Enthält keine nichttextilen Teile tierischen Ursprungs", en: "Contains no non-textile parts of animal origin"}},

    // Other
    SONSTIGES: {key: "SONSTIGES", label: {de: "Sonstiges", en: "Other"}}
};